/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "crud-framework"
include(":crud-framework-web")
include(":crud-framework-test")
include(":crud-framework-mongo-connector")
include(":crud-framework-core")
include(":crud-framework-hibernate5-connector")
