/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("dev.krud.crudframework.java-conventions")
}

dependencies {
    implementation(project(":crud-framework-core"))
    implementation("org.springframework.boot:spring-boot-autoconfigure:2.5.2")
    implementation("dev.krud:shapeshift")
    implementation("dev.krud:spring-boot-starter-shapeshift")
}

description = "crud-framework-test"
