/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("dev.krud.crudframework.java-conventions")
}

dependencies {
    implementation("dev.krud:shapeshift")
    implementation("dev.krud:spring-boot-starter-shapeshift")
    implementation("dev.krud:spring-componentmap")
    implementation("org.springframework.boot:spring-boot-starter")
    implementation("org.springframework:spring-tx")
    implementation("org.aspectj:aspectjweaver")
    implementation("org.hibernate.validator:hibernate-validator")
    implementation("com.github.tomas-langer:chalk")
    compileOnly("net.sf.ehcache:ehcache:2.10.9.2")
}

description = "crud-framework-core"
