/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("dev.krud.crudframework.java-conventions")
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web:2.5.2")
    implementation(project(":crud-framework-core"))
    implementation("org.reflections:reflections:0.10.2")
    implementation("com.google.code.gson:gson")
    implementation("dev.krud:shapeshift")
    implementation("dev.krud:spring-boot-starter-shapeshift")
    testImplementation(project(":crud-framework-test"))
}

description = "crud-framework-web"
